import { type Chat, type ChatFolder } from './types';

export const chatFolders: ChatFolder[] = [
  { id: 'all', title: 'Все чаты', icon: 'chats', unreadCount: 1 },
  { id: 'news', title: 'Новости', icon: 'news' },
  { id: 'gti', title: 'GTI Radio', icon: 'radio' },
  { id: 'ucrm', title: 'U-CRM', icon: 'folder' },
  { id: 't6', title: 'T6 и Жесть', icon: 'folder' },
  { id: 'lime', title: 'Lime Master', icon: 'folder' },
];

const colors = {
  blue: '#64B5F6',
  purple: '#BA68C8',
  teal: '#4DB6AC',
  orange: '#FFB74D',
  pink: '#F06292',
  green: '#81C784',
  indigo: '#7986CB',
  red: '#E57373',
  cyan: '#4DD0E1',
  amber: '#FFD54F',
};

export const mockChats: Chat[] = [
  {
    id: 'general',
    title: 'General',
    avatar: 'G',
    avatarColor: colors.blue,
    type: 'group',
    folder: 'all',
    lastMessage: 'Добро пожаловать в канал',
    lastMessageTime: '12.05.2025',
    unreadCount: 0,
    pinned: true,
    messageCount: 128,
  },
  {
    id: 'v3439',
    title: 'Посетитель №3439',
    avatar: 'П',
    avatarColor: colors.purple,
    type: 'private',
    folder: 'ucrm',
    lastMessage: 'Клиент пишет в чат: Здравствуйте',
    lastMessageTime: '13.05.2025',
    lastMessageOutgoing: true,
    lastMessageStatus: 'read',
    unreadCount: 0,
    messageCount: 6,
  },
  {
    id: 'v3898',
    title: 'Посетитель №3898',
    avatar: 'П',
    avatarColor: colors.teal,
    type: 'private',
    folder: 'ucrm',
    lastMessage: 'ИИ ответил в чат клиенту: Добрый день!',
    lastMessageTime: '13.05.2025',
    lastMessageOutgoing: true,
    lastMessageStatus: 'read',
    unreadCount: 0,
    messageCount: 3,
  },
  {
    id: 'v3915',
    title: 'Посетитель №3915',
    avatar: 'П',
    avatarColor: colors.orange,
    type: 'private',
    folder: 'ucrm',
    lastMessage: 'ИИ ответил в чат клиенту: Добрый день! 😊',
    lastMessageTime: '15.05.2025',
    lastMessageOutgoing: true,
    lastMessageStatus: 'read',
    unreadCount: 0,
    messageCount: 4,
  },
  {
    id: 'v3886',
    title: 'Посетитель №3886',
    avatar: 'П',
    avatarColor: colors.pink,
    type: 'private',
    folder: 'ucrm',
    lastMessage: 'Клиент пишет в чат: Подскажите по тарифу',
    lastMessageTime: '14.05.2025',
    unreadCount: 1,
    messageCount: 2,
  },
  {
    id: 'v3871',
    title: 'Посетитель №3871',
    avatar: 'П',
    avatarColor: colors.green,
    type: 'private',
    folder: 'ucrm',
    lastMessage: 'ИИ ответил в чат клиенту: Конечно, помогу',
    lastMessageTime: '14.05.2025',
    lastMessageOutgoing: true,
    lastMessageStatus: 'delivered',
    unreadCount: 0,
    messageCount: 5,
  },
  {
    id: 'v3864',
    title: 'Посетитель №3864',
    avatar: 'П',
    avatarColor: colors.indigo,
    type: 'private',
    folder: 'ucrm',
    lastMessage: 'Клиент пишет в чат: Есть свободные слоты?',
    lastMessageTime: '13.05.2025',
    unreadCount: 0,
    messageCount: 8,
  },
  {
    id: 'v3850',
    title: 'Посетитель №3850',
    avatar: 'П',
    avatarColor: colors.red,
    type: 'private',
    folder: 'ucrm',
    lastMessage: 'ИИ ответил в чат клиенту: Передаю оператору',
    lastMessageTime: '12.05.2025',
    lastMessageOutgoing: true,
    lastMessageStatus: 'read',
    unreadCount: 0,
    messageCount: 11,
  },
  {
    id: 'v3842',
    title: 'Посетитель №3842',
    avatar: 'П',
    avatarColor: colors.cyan,
    type: 'private',
    folder: 'ucrm',
    lastMessage: 'Клиент пишет в чат: Спасибо!',
    lastMessageTime: '12.05.2025',
    unreadCount: 0,
    messageCount: 3,
  },
  {
    id: 'news1',
    title: 'Новости компании',
    avatar: 'Н',
    avatarColor: colors.amber,
    type: 'channel',
    folder: 'news',
    lastMessage: 'Обновление тарифов с 1 июня',
    lastMessageTime: 'Вчера',
    unreadCount: 3,
    messageCount: 42,
  },
  {
    id: 'gti1',
    title: 'GTI эфир',
    avatar: 'G',
    avatarColor: colors.blue,
    type: 'group',
    folder: 'gti',
    lastMessage: 'Ведущий: Начинаем прямой эфир',
    lastMessageTime: 'Пн',
    unreadCount: 0,
    messageCount: 210,
  },
];
