import { type Chat } from './types';

export const mockChats: Chat[] = [
  {
    id: '1',
    title: 'Алексей Петров',
    avatar: '🧑‍💻',
    type: 'private',
    lastMessage: 'Привет! Как дела с проектом?',
    lastMessageTime: '12:45',
    unreadCount: 2,
    userId: 'u1',
    online: true,
    pinned: true,
  },
  {
    id: '2',
    title: 'Frontend Team',
    avatar: '👥',
    type: 'group',
    lastMessage: 'Мария: Новый релиз завтра в 10:00',
    lastMessageTime: '12:30',
    unreadCount: 5,
    pinned: true,
  },
  {
    id: '3',
    title: 'Елена Смирнова',
    avatar: '👩‍🎨',
    type: 'private',
    lastMessage: 'Макеты готовы, посмотри когда будет время',
    lastMessageTime: '11:20',
    unreadCount: 0,
    userId: 'u3',
    online: false,
  },
  {
    id: '4',
    title: 'Дмитрий Козлов',
    avatar: '👨‍🔬',
    type: 'private',
    lastMessage: 'Спасибо за помощь!',
    lastMessageTime: '10:05',
    unreadCount: 0,
    userId: 'u4',
    online: true,
  },
  {
    id: '5',
    title: 'Design Club',
    avatar: '🎨',
    type: 'group',
    lastMessage: 'Анна: Кто идёт на конференцию?',
    lastMessageTime: 'Вчера',
    unreadCount: 12,
  },
  {
    id: '6',
    title: 'Ольга Иванова',
    avatar: '👩‍💼',
    type: 'private',
    lastMessage: 'Встреча перенесена на 15:00',
    lastMessageTime: 'Вчера',
    unreadCount: 0,
    userId: 'u6',
    online: false,
  },
  {
    id: '7',
    title: 'React Community',
    avatar: '⚛️',
    type: 'group',
    lastMessage: 'Mike: Check out the new RFC',
    lastMessageTime: 'Пн',
    unreadCount: 0,
  },
  {
    id: '8',
    title: 'Игорь Волков',
    avatar: '🧑‍🚀',
    type: 'private',
    lastMessage: 'Го в зал вечером?',
    lastMessageTime: 'Пн',
    unreadCount: 0,
    userId: 'u8',
    online: true,
  },
  {
    id: '9',
    title: 'SolidJS RU',
    avatar: '💠',
    type: 'group',
    lastMessage: 'Сергей: MobX + Solid это огонь',
    lastMessageTime: 'Вс',
    unreadCount: 3,
  },
  {
    id: '10',
    title: 'Наталья',
    avatar: '🌸',
    type: 'private',
    lastMessage: 'С днём рождения! 🎂',
    lastMessageTime: 'Сб',
    unreadCount: 0,
    userId: 'u10',
    online: false,
  },
];
